### ISSUE TITLE
Some Youtube videos will not play or just freeze

### ISSUE THREAD

**Issue by RushingWind** [ACK-J/Port_Authority#1]
I noticed right after loading Port Authority that some Youtube videos either won't play at all and others will just freeze. Here is an example of a video ... https://www.youtube.com/watch?v=tlR98APSmXw

I first load the network console and then start this video and then immediately see errors from the Port Authority extension. When I disable this extension, all the videos play fine. This problem doesn't happen on all videos but it happens enough where I have to disable this extension. I'm using the latest version of Firefox on Windows 10 desktop.

Otherwise, website browsing seems ok and I love seeing Port Authority working in the background. I really like the idea behind this extension and hope this little bug ca be fixed.

Thanks for all your hard work.

**Comment by ACK-J** [comment]
Thank you for reporting the issue and glad you like the project! I didn't know that it broke youtube but I have realised that it broke google slides pretty bad to the same unuseable form. I believe it has to do with my regex for matching private IPV6 addresses, for some reason it is matching on network connections google uses. This is my first javascript project so I'm still learning, if you have any reccomendations please submit a PR. I've worked a ton on this extension the last few days and need to finish some school work but will work to resolve it this weekend.

**Comment by ACK-J** [comment]
@RushingWind I have pushed fixes to the regex that I believe fixed your issue. Can you please test it again and make sure everything is good on your end?

**Comment by RushingWind** [comment]
I will test this and let you know what I find out. Thanks for all your help.

**Comment by RushingWind** [comment]
OK, I tried several YouTube videos and all play fine with no errors. I also
tried running the test sites you have listed on the Port Authority page on
Mozilla. Those tests also run without problems. So far, this extension
seems to be running without issues.

Thank you for your quick response and resolution. If I encounter any
unexpected issues along the way, I will let you know. I look forward to
future updates to this brilliant piece of work.


thanks again.

**Comment by ACK-J** [comment]
Thank you for the update and the kind words! I'll be working a lot more on making the extension look better, now that I am happy with the functionality. I'll be releasing 1.0.8 in a few minutes which simplifies part of the regex to make it more efficient and accurate. I'll close out this issue but if you find any other websites that break please feel free to re-open the issue and I will take a look.
