### ISSUE TITLE
[False Positive] identity.trimble.com -> localhost (SketchUp)

### ISSUE THREAD

**Issue by ph00lt0** [ACK-J/Port_Authority#15]
**The URL**
identity.trimble.com

**To Reproduce**
1. You will need SketchUp 2020 Desktop version to reproduce this false positive (free trail: https://www.sketchup.com/try-sketchup#for-personal)
2. When trying to login to the application it opens a browser window.
3. Login in to a Trimble account.
4. The website redirects to a local IP, set up by the SketchUp application to authenticate the app. The browser will show the Port Authority warning and log in process is broken. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 91

**Additional context**
In relation to #10 it would be nice to have the option to allow redirecting from certain domains to a local IP and have a per-configured whitelist. 

Interestingly UBo (with LAN filter enabled) does not block this redirection login method.

**Comment by ACK-J** [comment]
Hey @ph00lt0 hopefully I will have a big update out soon with the option to whitelist sites like this. It definitely is needed in some situations. I’ll keep you posted

**Comment by ph00lt0** [comment]
@ACK-J, not 100% sure but I think the difference between uBo and PortAuthority is that the latter one blocks redirects to the localhost where as uBo only blocks the third party connections.

**Comment by ACK-J** [comment]
The domain whitelist feature is now live in v2.0.0 https://github.com/ACK-J/Port_Authority/releases/tag/2.0.0
Your browser should automatically update the extension within a day or so
