### ISSUE TITLE
[BUG] Version 1.1.0 Crashes Firefox

### ISSUE THREAD

**Issue by blassepl** [ACK-J/Port_Authority#18]
**Describe the bug**
After updating extension to 1.1.0 Firefox 92.0.1 crashes

**To Reproduce**
1. Install Port_Authority 1.1.0
2. Wait 15 seconds

**Expected behavior**
It should not crash ;)

**Screenshots**
No screenshots, log attached - it crashes without any tab open, just after starting FF. Disabling Port_Authority solves the issue.
[crash_log.txt](https://github.com/ACK-J/Port_Authority/files/7253951/crash_log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1237
 - Browser: Firefox 92.0.1

**Comment by ACK-J** [comment]
Well shit... thats not good

**Comment by ACK-J** [comment]
![image](https://user-images.githubusercontent.com/60232273/135325616-68e97e39-c653-4c8b-86f9-a8c396c69ed1.png)
So I'm not able to reproduce the crash you are talking about. I installed all the addons you are using as well to check if there was an issue there. Any ideas on how to more reliably reproduce the crash?

**Comment by blassepl** [comment]
Hmm. That's both good and bad news. It seems that some of my hardened config is interfering. I will have to track it down on my own, but I will share the result when I will find something.

**Comment by ACK-J** [comment]
Thanks for the heads up and I'd be interested into what you find. Sorry its broken 😅

**Comment by ACK-J** [comment]
I have just updated PortAuthority with a few fixes. Would you be able to update the extension in your browser and let me know if version 1.1.1 still crashes your machine?

**Comment by blassepl** [comment]
Working fine now. Thx.
