### ISSUE TITLE
[BUG] Port Authority 1.1.1 crashes on Firefox 94.0.2 (Linux)

### ISSUE THREAD

**Issue by canihavesomecoffee** [ACK-J/Port_Authority#19]
**Describe the bug**
After upgrading to Firefox 94.0.2, Firefox continues to crash while Port Authority is enabled. Once it's disabled, the problem disappears.

I saw the next message if I wanted to report the issue to Firefox:
> MozCrashReason: MOZ_CRASH(IPC message size is too large)

**To Reproduce**
1. Upgrade to Firefox 94.0.2

**Expected behavior**
No crash of Firefox

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Manjaro (Linux)
 - Browser: Firefox
 - Version: 94.0.2 (64-bit)

**Additional context**

**Comment by ACK-J** [comment]
Looking into it now

**Comment by ACK-J** [comment]
I am unable to reproduce the bug. Would you be able to provide me a little more context such as what other addons do you have installed or the output from the extension debugger in `about:debugging` -> `This Firefox` -> `Port Authority` -> `Inspect`

So far I have installed a fresh version of firefox 94.0.2 with only Port Authority installed and seeing no issues.

**Comment by canihavesomecoffee** [comment]
I tried doing that, but it seems that disabled extensions are not listed in there :(

The moment I enable the extension again, I have about 2-3 seconds before Firefox crashes for me, making debugging not that easy.

I loaded the xpi as a temporary addon, and then I was (quickly) able to screenshot this:
![image](https://user-images.githubusercontent.com/7365586/143266224-a00d5819-df55-4972-b2b1-c2224eb75777.png)

And that was followed by a crash within a couple of seconds...

I'll try to quickly click inspect on that next...

Wrt other addons: if I start Firefox in Safe Mode, disable all addons it doesn't crash, if I enable Port Authority as single addon, it also crashes, so my guts would say other addons aren't involved.

**Comment by canihavesomecoffee** [comment]
Closing, a reinstall (removing the addons, restarting ff and reinstalling) seems to have fixed the issue.

Don't know why the crashing occurred, but it's fixed for me now...

**Comment by ACK-J** [comment]
Glad you got it fixed :)

**Comment by HifeFish** [comment]
I have had the same behaviour show up for me yesterday independent of any updates on Firefox 88.0.1 on Ubuntu 16.04. This Firefox version was installed back in May. I cannot tell what triggered the problem. It was resolved after reinstalling Port Authority.

**Comment by ACK-J** [comment]
@HifeFish Interesting, this is the first report of this issue not on 94.0.2 I'll keep looking into it but debugging is especially hard since I can't reproduce the issue myself

**Comment by HifeFish** [comment]
Since it is no longer happening after reinstalling, I cannot run any tests, but this is the output during the crash when I ran firefox from the terminal:

```
[GFX1-]: glxtest: libEGL missing eglGetDisplayDriverName 
ExceptionHandler::GenerateDump cloned child 25398 
ExceptionHandler::SendContinueSignalToChild sent continue signal to child 
ExceptionHandler::WaitForContinueSignal waiting for continue signal... 
Exiting due to channel error. 
Exiting due to channel error. 
Exiting due to channel error. 
Exiting due to channel error.
```

**Comment by canihavesomecoffee** [comment]
The same error (channel error) was something I saw too.

**Comment by ACK-J** [comment]
I have still yet to figure out what the underlying issue is :/
