### ISSUE TITLE
Toggle is not functional

### ISSUE THREAD

**Issue by ACK-J** [ACK-J/Port_Authority#2]
- The switch toggle does not disable the functionality of the addon

**Comment by laniakea64** [comment]
Hi @ACK-J , I'm interested in the idea of this addon but this bug is annoying.  If I can fix this, would it be helpful if I file a pull request?

**Comment by ACK-J** [comment]
@laniakea64 Hey, glad you like the project! I've been really busy lately and honestly pretty new to Javascript UI. I know that it is frustrating that the toggle switch doesn't work... It even annoys me. If you could find a fix and submit a pull request I would be very greatful. There are a lot of UI improvements I would like to add, working on getting some more people talented at javascript/HTMl/CSS on the project.
-Jack
