### ISSUE TITLE
[False Positive] fc01.deviantart.net

### ISSUE THREAD

**Issue by laniakea64** [ACK-J/Port_Authority#21]
**The URL**
[The URL to go to which triggered this false positive.](https://forums.mozillazine.org/viewtopic.php?f=11&t=3076617)

**To Reproduce**
1. Go to aforementioned URL
2. Watch Port Authority block the image in the final post (by LIMPET235) from fc01.deviantart.net as a port scan attempt.  But neither that URL nor the domain's DNS lookup has any reference to anything local here.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Xubuntu 20.04 64-bit
 - Browser Firefox 95.0.1
 - Version Port Authority 1.1.1

**Smartphone (please complete the following information):**
n/a

**Additional context**
Also, sometimes most of the browser will hang and be unresponsive while trying to load that URL.  It prevents opening other extensions' popups.  This happens even if Port Authority's blocking switch is toggled off from its popup.  Only when Port Authority is completely disabled from Add-ons Manager did this stop happening and the page load as expected.

I did not see any related messages in about:debugging console for Port Authority.

**Comment by ACK-J** [comment]
Hey, doing some digging into this issue. It looks like the subdomain of that URL was being picked up by the IPV6 portion of the regex which is unfortunate. I'll make a fix for this.
![image](https://user-images.githubusercontent.com/60232273/181676408-7fc11f7c-77d3-4a56-bb6f-83fe7073bb1d.png)

**Comment by ACK-J** [comment]
This issue has been resolved with v1.1.2
