### ISSUE TITLE
[BUG] Toggles render black on black

### ISSUE THREAD

**Issue by joshudson** [ACK-J/Port_Authority#23]
**Describe the bug**

I need to use black theme on everything; all backgrounds are black, all text is white. Port authority doesn't handle this

**To Reproduce**

Edit | Settings | Colors | Background: Black, Text: White, Allow Pages to set their own: Never
Open Port Authority's config

**Expected behavior**

Buttons render 

**Screenshots**

![portauthoritybuttons](https://user-images.githubusercontent.com/16249210/162234218-693c36d0-2aac-4686-84b8-5027d76cb58b.png)

**Desktop (please complete the following information):**

Known Affected: Linux x64, Windows x64
Probably all are affected

**Comment by jhudsoncedaron** [comment]
@ACK-J : I'm not sure if that's an image or an HTML item. To fix image, make it a not image. To fix text items, if you just took off the color declarations altogether it would probably work. uBlockOrigin works correctly; maybe look at how it does it.
