### ISSUE TITLE
[BUG] Discord Endpoint

### ISSUE THREAD

**Issue by Fryni5** [ACK-J/Port_Authority#24]
an endpoint that can be added to the list...
when I use an invite from some server on discord (*Example Link:* discord.com/invite/*ServerID* or discord.gg/invite/*ServerID* )
the extension blocks about 10 port scans and that's the first time I got that many
*I'm not knowledgable about this topic so idk if this is the right place to post this*

**Comment by ACK-J** [comment]
This is intended functionality and would be better solved with an option to whitelist certain domains. For a temporary fix, turn off the global "Blocking"  when discord needs to connect to your local server.

**Comment by ACK-J** [comment]
The domain whitelist feature is now live in v2.0.0 https://github.com/ACK-J/Port_Authority/releases/tag/2.0.0
Your browser should automatically update the extension within a day or so
