### ISSUE TITLE
Change ethernet icon from black to something else

### ISSUE THREAD

**Issue by peepopoggers** [ACK-J/Port_Authority#8]
On the readme, the ethernet icon blends in with dark theme.
You should change it to something both light and dark theme can see such as orange.

;)

**Comment by ACK-J** [comment]
I mean I love dark themes but it looks fine with the default theme and I kinda like the color scheme so I'm going to keep it the way it is. The GUI is red so orange on red is not a great mix

**Comment by peepopoggers** [comment]
You could use red then

**Comment by ACK-J** [comment]
Changed it to red

**Comment by peepopoggers** [comment]
:+1:
